### ISSUE TITLE
Add PNG support

### ISSUE THREAD

**Issue by baamenabar** [sadok-f/fly-image#10]
maybe with Zopfli for compression
more: https://ariya.io/2016/06/using-zopfli-to-optimize-png-images

**Comment by sadok-f** [comment]
as it says on the blog: `Note that since Zopfli’s compressor is a CPU-intensive operation, the process often takes a few seconds.`, we tested it and it took too much time to process one single image, it a good solution as it's lossless but I think it only works as a background process to optimize a folder of png images.
